Feature/basic form structure
isdi-coders-2022/The-Blind-Side-202204-bcn pull request #79
Opened 2022-05-07 22:31 UTC by ccbabcn

2022-05-07 22:34 UTC, Marianlopig approved these changes
maquina!

2022-05-07 22:46 UTC, Marianlopig requested changes

2022-05-07 22:46 UTC, Marianlopig commented on src/components/FormComponent/FormComponent.js
> +    id: `created${favouritedCharacters.length}`,
no hace falta incluir el id para que el backend genere uno :)

2022-05-08 09:49 UTC, TomasSkylab approved these changes

2022-05-08 10:52 UTC, Marianlopig approved these changes

2022-05-08 10:52 UTC, merged